mode: backtest # backtest, live
start_date: 2025-05-23
end_date: 2025-05-24
primary_interval: 5m
initial_cash: 1000
margin_requirement: 1.0
show_reasoning: false
show_agent_graph: true
signals:
  intervals: [1h, "2h", "30m", "15m", "5m", "12h"]
  tickers: ["ETHUSDT"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]

