mode: live
start_date: 2025-05-23
end_date: 2025-05-24
primary_interval: 3m
initial_cash: 100
margin_requirement: 0.2
show_reasoning: false
show_agent_graph: false
signals:
  intervals: ["30m","15m","5m","3m"]
  tickers: ["ETHUSDC"]
  strategies: ['MacdStrategy', "RSIStrategy"]