mode: live
start_date: 2025-06-19T04:35:00 #YYYY-MM-DDTHH:MM:SS
end_date: 2025-06-21T10:00:00 #YYYY-MM-DDTHH:MM:SS
primary_interval: 1m
initial_cash: 100
margin_requirement: 0.2
show_reasoning: false
show_agent_graph: false
signals:
  intervals: ["15m","5m","3m","1m"]
  tickers: ["ETHUSDC"]
  strategies: ['MacdStrategy', "RSIStrategy"]