mode: live
start_date: 2025-05-23
end_date: 2025-05-24
primary_interval: 5m
initial_cash: 10
margin_requirement: 0.2
show_reasoning: false
show_agent_graph: true
signals:
  intervals: ["12h", "2h", "1h", "30m", "15m", "5m"]
  tickers: ["ETHUSDC"]
  strategies: ['MacdStrategy']
# , "RSIStrategy"]